### ISSUE TITLE
Please add licensing information

### ISSUE THREAD

**Issue by mafr** [abendt/hibernate4-maven-plugin#1]
Hi,

thanks a lot for taking the time to write this really useful plugin! I haven't seen any licensing information though, so I'm not sure if I'm allowed to use it at work. The Apache License would be really great, it's what most Maven plugins use :)

Thank you,
  Matthias

**Comment by abendt** [comment]
i have added a license. lgpl. is that ok too?
see: https://github.com/akquinet/hibernate4-maven-plugin

**Comment by mafr** [comment]
Sure, that works, too. Thank you!
